// Generated by BUCKLESCRIPT VERSION 5.0.6, PLEASE EDIT WITH CARE
'use strict';

var Utils = require("../Utils.js");
var React = require("react");

function Footer(Props) {
  var itemLength = Props.itemLength;
  var match = itemLength <= 1;
  var format = Utils.str(String(itemLength) + ("item" + (
          match ? "" : "s"
        )));
  return React.createElement("footer", undefined, format);
}

var make = Footer;

exports.make = make;
/* react Not a pure module */
